# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: first job
    steps:
    - bash: echo build first job 
  - job: second job 
    steps:
    - bash: echo build second job
- stage: deploy 
  dependsOn:
  - build
  - testQA
  jobs:
  - job: deploy job one
    steps: 
    - bash: echo deploy Job 
- stage: testQA
  dependsOn: build
  jobs:
  - job: QA first Job 
    steps: 
    - bash: echo QA first job 